### ISSUE TITLE
It is not clear in docs how to control the toast states on-demand instead of auto behavior!

### ISSUE THREAD

**Issue by Hussseinkizz** [emilkowalski/sonner#173]
There should be a way to promptly show or hide the toast when I want and how I want, say I have my own logic to handle when I want those states to happen!

So that I don't have to do something like this below say I want it to load forever until I promptly turn it to success or error:

   const id = toast.loading("Loading...", { duration: Infinity });

**Comment by fecony** [comment]
`loading` method is already implemented but Yes, docs are missing it and you are right about infinite duration

Here is codesandbox example how to use it for others https://codesandbox.io/s/headless-flower-lpygy3?file=/src/App.js
But the problem is that I have to set `duration` to Infinity number as by default it will close after 4 seconds, that I believe should not happen for this type of toast

It looks like it should not happen from the source code, but maybe I'm missing something
https://github.com/emilkowalski/sonner/blob/main/src/index.tsx#L152

**Comment by emilkowalski** [comment]
I've updated the docs include a section about the loading toast.

As for the `duration`, it's by design.

**Comment by Hussseinkizz** [comment]
I know you closed this and I have not been on this project where am trying to use this lately but you didn't demonstrate this usage in docs as claimed, am not saying that of using a promise, am saying creating a toastId and doing stuff with it, that's no where in docs!!!
