### ISSUE TITLE
[Feature Request]: Add option to choose swipe dismiss direction

### ISSUE THREAD

**Issue by RochaSamuel** [emilkowalski/sonner#274]
Today we have swipe dismiss in vertical direction. Would be nice to add one property to chose the swipe to dismiss action direction like 'vertical', 'horizontal' and other option to allow the both directions.

**Comment by emilkowalski** [comment]
It has only vertical swipe direction, because I wanted it to have spacial consistency I described [here](https://emilkowal.ski/ui/building-a-toast-component). It could be unintuitive for the users to swipe horizontally when the toast comes from the bottom. Considering this toast library is opinionated, I'd like to keep it the way it is. Thank you for the suggestion tho!

**Comment by sshmaxime** [comment]
Hey @emilkowalski , thanks for this super library ! 

Do you really not want to reconsider this ? You could just let the default the way it is today but still allow one to customize the direction at will ? I feel like the swiping bot thing to dismiss is pretty counter-intuitive. Wdyt ?

**Comment by RobinLbt** [comment]
I agree with @sshmaxime 

Swiping right is more intuitive than swiping up or down to dismiss

I use Sonner in production, and our users are always trying to dismiss toasts by swiping right instead of up
