### ISSUE TITLE
HTML Validation fails in Cypress

### ISSUE THREAD

**Issue by manskron** [emilkowalski/sonner#29]
When running Cypress tests with the html-validate plugin, tests will fail because of the following:
![Screenshot 2023-03-09 at 09 21 14](https://user-images.githubusercontent.com/3447001/223973528-ee11cd3b-5933-4d78-aa41-cff041d81c99.png)

It seems that using `<section>` is preferred over `<div role="region">`

**Comment by emilkowalski** [comment]
Is there a way to silence this error?  That div is only used as a styling wrapper and it's not really a section (no heading, toaster can be empty sometimes).

**Comment by u840903** [comment]
There is a way to silence errors, but are you sure section isn't the more appropriate element?

**The native element equivalent of `<div role="region">` is `<section>` according to.**
https://html-validate.org/rules/prefer-native-element.html
"While WAI-ARIA describes many roles which can provide semantic information about what the element represents. Support for roles is varying and since HTML5 has many native equivalent elements it is better to use the native when possible."

Role | Element
-- | --
... | ...
radio | input
**region** | **section**
table | table
... | ...

**Sections does not need a heading according to.**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#using_a_section_without_a_heading
"The `<section>` element represents a generic standalone section of a document, which doesn't have a more specific semantic element to represent it. Sections should always have a heading, **with very few exceptions.**"

**Comment by emilkowalski** [comment]
After doing some more research I decided to replace the div with a `section`. Thank you for reporting this @manskron, and thank you for chiming in @u840903.
Fixed in #38

**Comment by u840903** [comment]
Thank you @emilkowalski! Much appreciated!

**Comment by manskron** [comment]
Thanks @emilkowalski
