### ISSUE TITLE
global toastOptions for each toast type

### ISSUE THREAD

**Issue by MarkLyck** [emilkowalski/sonner#291]
### Describe the feature / bug 📝:

As a developer I'd like to be able to make my error toasts (or any other type) have different toastOptions without having to manually add them to every single `toast` instance.

In my case, I want all of my error toasts to have a longer duration and have a closeButton. Adding manual options in 100+ places doesn't seem like a great way to do it. 1 global option that only affects a specific toast type would be great.

**Comment by dclark27** [comment]
@MarkLyck You could re-export your toast handlers like so:

```typescript
export const errorToast = (
  message: ReactNode,
  data?: ExternalToast | undefined
) => {
  // Custom options in the second half that cannot be overwritten
  return toast.error(message, { ...data, dismissible: false })
  
  // or custom options in the first half that can be overwritten
  return toast.error(message, { dismissible: false, ...data })
}
```

**Comment by MarkLyck** [comment]
@dclark27 Yeah that's definitely a possible workaround.

But I don't want to have to import my error toast from a different file than my other toasts from sonner. So realistically you'd end up doing this for all the toast options to keep consistency.

It's just nicer and more readable to import the toast directly from `sonner` which means developers instantly know where to go look for docs and how to use it.

I still think adding a better config option to the library itself would be a better solution.

**Comment by emilkowalski** [comment]
This would add some complexity to the code and I consider this an edge-case that is not worth adding IMO. You can do the same thing by creating wrapper reusable wrapper functions around the toast function.

**Comment by little077** [comment]
Due to my modification of the centering style of the component library and my initial lack of understanding of the default drag behavior, I only realized later on in my project that there was a message indicating that clicking would move to the right and slide down. I thought this was my fault, but when I made the changes, I realized that this attribute could not be added to the global level. This caused me to painfully encapsulate hooks to manually replace existing code globally, and some of them were directly used in objects. In order to be compatible with old logic, I had to manually add configurations or modify existing code.

**Comment by little077** [comment]
function useToast(): UseToastReturn {
  const createToast =
    (type: ToastTypes) => (message: titleT, data?: ExternalToast) => {
      toast[type](message, { dismissible: false, ...data })
    }
  return {
    success: createToast("success"),
    info: createToast("info"),
    warning: createToast("warning"),
    error: createToast("error")
  }
}It's probably packaged like this
