### ISSUE TITLE
richColor prop not working

### ISSUE THREAD

**Issue by ghost** [emilkowalski/sonner#346]
### Describe the feature / bug 📝:

Toaster richColors attribute doesn"t make any effect, the toast keep showing native without colors

### Steps to reproduce the bug 🔁:

1. 
![image](https://github.com/emilkowalski/sonner/assets/68515775/e04391a6-c4d6-4e42-bba6-2c8c22e510fb)

2.
![image](https://github.com/emilkowalski/sonner/assets/68515775/339f94c2-fa4f-421b-9091-ca980135b953)

3.
![image](https://github.com/emilkowalski/sonner/assets/68515775/ef31c7d6-2e17-4e04-9a3c-68e15b092214)

**Comment by reboottime** [comment]
You may also want to give a package version or a codesandbox  to host the sample code.

Looking at the comment above, I think it should work idealy.

**Comment by carlosmfreitas2409** [comment]
The same problem is happening here too.
Sonner version 1.4.0

**Comment by AhmedAlbarghouti** [comment]
That's odd, even though it seems like a toastInfo is the one that fired, the richColors flag doesnt seem to effect it either.
I had this issue today but right before I was going to comment on this I found the issue was a on my end.
Probably need to go over your code again and if it still persists then provide a sandbox to replicate this issue.

**Comment by lyorb** [comment]
I have exactly the same problem, although the colors were displayed correctly yesterday.
