### ISSUE TITLE
Bug: top positions have opposite swipe to dismiss directions

### ISSUE THREAD

**Issue by omgcx1222** [emilkowalski/sonner#523]
pnpm install sonner --> `"sonner": "^1.7.0"`
`<Toaster position="top-right" />`

I saw that this bug was solved in #513 , but the problem still occurred after I installed version 1.7.0. 
I went back to version 1.5.0, It is normal to dismiss the top position

**Comment by hunterrmartinn** [comment]
This is interesting because if you view the production builds for the website [here](https://github.com/emilkowalski/sonner/deployments/Production), my fix in #513 does work. I noticed that it doesn't work on the production version of the website even though it does work in the v1.7.1 deployment, which should be production.

- ❌ [sonner.emilkowal.ski](https://sonner.emilkowal.ski)
- ✅ [v1.7.1](https://sonner-mge3lrze5-emilkowalski-s-team.vercel.app/)
- ✅ [fix: styles.css is not declared in package.json](https://sonner-a304i0f9p-emilkowalski-s-team.vercel.app/)
- ✅ [Fix top position swipe direction](https://sonner-1hqhmaa2c-emilkowalski-s-team.vercel.app/)
- ❌ [v1.7.0](https://sonner-m3glncxun-emilkowalski-s-team.vercel.app/)

CC: @emilkowalski any ideas here?

**Comment by omgcx1222** [comment]
> This is interesting because if you view the production builds for the website [here](https://github.com/emilkowalski/sonner/deployments/Production), my fix in #513 does work. I noticed that it doesn't work on the production version of the website even though it does work in the v1.7.1 deployment, which should be production.
> 
> * ❌ [sonner.emilkowal.ski](https://sonner.emilkowal.ski)
> * ✅ [v1.7.1](https://sonner-mge3lrze5-emilkowalski-s-team.vercel.app/)
> * ✅ [fix: styles.css is not declared in package.json](https://sonner-a304i0f9p-emilkowalski-s-team.vercel.app/)
> * ✅ [Fix top position swipe direction](https://sonner-1hqhmaa2c-emilkowalski-s-team.vercel.app/)
> * ❌ [v1.7.0](https://sonner-m3glncxun-emilkowalski-s-team.vercel.app/)
> 
> CC: @emilkowalski any ideas here?

thank, I just noticed that it was fixed in the 1.7.1 production release
