### ISSUE TITLE
Height of the promise toast changes on mouse hover

### ISSUE THREAD

**Issue by LunaTK** [emilkowalski/sonner#66]
Hi, thanks for making an awesome toaster!

https://github.com/emilkowalski/sonner/assets/15868333/f1394e44-b4d5-405e-b0f3-48839461967e

Tested today (May 14th) at https://sonner.emilkowal.ski/ using macOS Chrome 113.0.5672.92(x86_64)

**Comment by Ncookiez** [comment]
Was going to make an issue on a similar problem, but I guess I'll piggyback off this one since it may be the same underlying issue.

When hovering over any toast that has been resized vertically in any way, its interactions can be pretty buggy.

I've created a small codesandbox [here](https://codesandbox.io/s/sonner-resizing-issue-1ig082) to show this in practice.

It is present in regular toasts as well as custom toasts.

It looks like it's returning to its original height on hover?

**Comment by joaom00** [comment]
@Ncookiez I think your issue is different because you change the initial height later and sonner doesn't watch height mutations

**Comment by Ncookiez** [comment]
> @Ncookiez I think your issue is different because you change the initial height later and sonner doesn't watch height mutations

Sorry for hogging the thread then - but do you know if there is a known workaround (other than making the content height the same I guess)? Or a way to update/re-render the toasts on content update?

Or should the toast be deleted and re-created as a different, entirely new toast when the content/height is updated?

**Comment by joaom00** [comment]
nothing comes to mind now unfortunately

**Comment by emilkowalski** [comment]
This was fixed in #69.

@Ncookiez We should listen to height changes and update the state accordingly. I've added an issue here - https://github.com/emilkowalski/sonner/issues/70.
